### ISSUE TITLE
supabase is undefined (when using with quasar)

### ISSUE THREAD

**Issue by bangdragon** [supabase-community/vue-supabase#13]
I use quasar.
And follow the guide here 
But get error: supabase is undefined

**Comment by scottrobertson** [comment]
Can you provide some more info, including examples of your code you are running?

**Comment by bangdragon** [comment]
Here is the code:
```
import { boot } from 'quasar/wrappers'
import supabaseServices from '../services/supabase'
import supabaseConfig from '../services/supabase/supabaseConfig'
// alert(JSON.stringify(supabaseConfig)) ok
import VueSupabase from 'vue-supabase'
import { useSupabase } from 'vue-supabase';

// "async" is optional;
// more info on params: https://v2.quasar.dev/quasar-cli/boot-files
export default boot(async ( { app, store, router } ) => {
  // something to do
  app.use(VueSupabase, {
    supabaseUrl: supabaseConfig.supabaseUrl,
    supabaseKey: supabaseConfig.supabaseAnonKey,
    supabaseOptions: supabaseConfig.supabaseOptions
  })
  const supabase = useSupabase()
  alert('supabase: ' + supabase)
})
```

**Comment by scottrobertson** [comment]
@sduduzog any ideas?

**Comment by sduduzog** [comment]
@scottrobertson At this point, no. I've never used Quasar... but I have 2 suggestions for @bangdragon to try out, and a couple of questions
1) Try using a single line for your import i.e. `import VueSupabase, { useSupabase } from 'vue-supabase`
2) Assuming that `app` is the vue instance, try using supabase from there i.e. `app.$supabase` but I'm skeptical here with this usage, if the first suggestion didn't fix your problem, try see if you can use any other hook from where you're trying to access supabase. 

If the above didn't work, I will need help reproducing this, which will require a public repo where this issue is apparent

**Comment by sduduzog** [comment]
@bangdragon I just tried this out in the most simplest way possible withing my Vue 3 project where I'm using `vue-supabase` without any issues 
![image](https://user-images.githubusercontent.com/48126337/134773011-6b27b173-2417-4191-86ae-5285df624b7b.png)

And I also get undefined 
![image](https://user-images.githubusercontent.com/48126337/134773026-688786de-4d3e-4ad5-b3f2-26c53a6c336b.png)


I will assume that this is either one of two reasons. 1) Either you're trying to use supabase when its not yet setup by vue (higly unlikely though) and 2) useSupabase uses `provide/inject` which works withing the context of the apps instance or its children. Calling `app.use` sets the plugin to that vue instance and you, like me in these screenshots, are trying to access it outside the instance to which it was created.

Try `useSupabase()` in any vue component and see if it works or not

**Comment by bangdragon** [comment]
> @bangdragon I just tried this out in the most simplest way possible withing my Vue 3 project where I'm using `vue-supabase` without any issues
> ![image](https://user-images.githubusercontent.com/48126337/134773011-6b27b173-2417-4191-86ae-5285df624b7b.png)
> 
> And I also get undefined
> ![image](https://user-images.githubusercontent.com/48126337/134773026-688786de-4d3e-4ad5-b3f2-26c53a6c336b.png)
> 
> I will assume that this is either one of two reasons. 1) Either you're trying to use supabase when its not yet setup by vue (higly unlikely though) and 2) useSupabase uses `provide/inject` which works withing the context of the apps instance or its children. Calling `app.use` sets the plugin to that vue instance and you, like me in these screenshots, are trying to access it outside the instance to which it was created.
> 
> Try `useSupabase()` in any vue component and see if it works or not

But I need to use supabase.auth in this boot file

**Comment by sduduzog** [comment]
Could you please provide a repository to reproduce this @bangdragon

**Comment by sduduzog** [comment]
Also pardon the question, I just want to understand, why would you want to use auth within a hook to register a plugin? @bangdragon

**Comment by bangdragon** [comment]
> Also pardon the question, I just want to understand, why would you want to use auth within a hook to register a plugin? @bangdragon

I want to track auth state change.
```
supabase.auth.onAuthStateChange((event, session) => {
      const user = session.user
   supabaseServices.handleOnAuthStateChanged(store, user, router)
    })
```

**Comment by scottrobertson** [comment]
> > Also pardon the question, I just want to understand, why would you want to use auth within a hook to register a plugin? @bangdragon
> 
> 
> 
> I want to track auth state change. So i will redirect user to login page if user signed out
> 
> ```
> 
> supabase.auth.onAuthStateChange((event, session) => {
> 
>       const user = session.user
> 
>    supabaseServices.handleOnAuthStateChanged(store, user, router)
> 
>     })
> 
> ```

I would put that in the 'created' of your application. https://stackoverflow.com/questions/47535737/where-to-place-firebase-auth-onauthstatechanged-in-vuejs

**Comment by bangdragon** [comment]
> > > Also pardon the question, I just want to understand, why would you want to use auth within a hook to register a plugin? @bangdragon
> > 
> > 
> > I want to track auth state change. So i will redirect user to login page if user signed out
> > ```
> > 
> > supabase.auth.onAuthStateChange((event, session) => {
> > 
> >       const user = session.user
> > 
> >    supabaseServices.handleOnAuthStateChanged(store, user, router)
> > 
> >     })
> > ```
> 
> I would put that in the 'created' of your application. https://stackoverflow.com/questions/47535737/where-to-place-firebase-auth-onauthstatechanged-in-vuejs

Quasar works as the way I am using, not the vuejs usual way

**Comment by sduduzog** [comment]
> Quasar works as the way I am using, not the vuejs usual way

In that case, there really isn't much we can help with. The plugin is made to work with VueJS as it does, This sounds more like an issue specific to Quasar and using basic Vue plugins with it.

I suggest that you install `@supabase/supabase-js` and use it for your usecase.

I still feel like you're misusing the plugin or you're using it in the wrong place but I can't be sure as I've stated, have no experience working with Quasar so I might be wrong. 

We can leave this issue open just in case someone else has had experience in the area or rather another person has ran into the same issue.

@bangdragon Might I suggest you reach out to the framework's community as they might be better help with finding a solution to your issue?

**Comment by bangdragon** [comment]
> > Quasar works as the way I am using, not the vuejs usual way
> 
> In that case, there really isn't much we can help with. The plugin is made to work with VueJS as it does, This sounds more like an issue specific to Quasar and using basic Vue plugins with it.
> 
> I suggest that you install `@supabase/supabase-js` and use it for your usecase.
> 
> I still feel like you're misusing the plugin or you're using it in the wrong place but I can't be sure as I've stated, have no experience working with Quasar so I might be wrong.
> 
> We can leave this issue open just in case someone else has had experience in the area or rather another person has ran into the same issue.
> 
> @bangdragon Might I suggest you reach out to the framework's community as they might be better help with finding a solution to your issue?

I will ask the quasar's community for this problem.
Thanks for your help so far

**Comment by scottrobertson** [comment]
> > > Quasar works as the way I am using, not the vuejs usual way
> 
> > 
> 
> > In that case, there really isn't much we can help with. The plugin is made to work with VueJS as it does, This sounds more like an issue specific to Quasar and using basic Vue plugins with it.
> 
> > 
> 
> > I suggest that you install `@supabase/supabase-js` and use it for your usecase.
> 
> > 
> 
> > I still feel like you're misusing the plugin or you're using it in the wrong place but I can't be sure as I've stated, have no experience working with Quasar so I might be wrong.
> 
> > 
> 
> > We can leave this issue open just in case someone else has had experience in the area or rather another person has ran into the same issue.
> 
> > 
> 
> > @bangdragon Might I suggest you reach out to the framework's community as they might be better help with finding a solution to your issue?
> 
> 
> 
> I will ask the quasar's community for this problem.
> 
> Thanks for your help so far

Let us know if you find a fix. It would be nice to support it too :)

**Comment by paolodina** [comment]
@bangdragon any news on this?

**Comment by sduduzog** [comment]
@paolodina Are you also facing the same issue?

**Comment by paolodina** [comment]
@sduduzog well I did 'till last time!
At the moment idk, I switched to Svelte in the meantime.
